language: csharp
solution: BabysitterKata.sln
install:
  - nuget restore BabysitterKata.sln
  - nuget install NUnit.Console -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BabysitterKata.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit-console.exe ./BabysitterKata.Tests/bin/Release/BabysitterKata.Tests.dll
notifications:
  pushover:
    api_key: a73mazs43fmmwdardg4ahf3ppifj15
    users:
      - udpa41py8vkzerk5t5dv4gk6vwqt96
