language: csharp
solution: BabysitterKata.sln
install:
  - nuget restore BabysitterKata.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BabysitterKata.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./BabysitterKata.Tests/bin/Release/BabysitterKata.Tests.dll